### ISSUE TITLE
Loved the idea....

### ISSUE THREAD

**Issue by rjhancock** [emilbaehr/automatic-app-landing-page#6]
so I made a GitLab CI/Pages version.

https://gitlab.com/rjhancock/app-landing-page

**Comment by emilbaehr** [comment]
Good idea!

**Comment by RichardFevrier** [comment]
Any plan to support both here?

**Comment by rjhancock** [comment]
For reference, this is all the CI file is:

```yaml
image: ruby:2.3

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install

test:
  stage: test
  script:
    - bundle exec jekyll build -d test
  artifacts:
    paths:
      - test
  except:
    - master

pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master
```
